baseURL = 'https://owasikohu.dev/'
languageCode = 'ja'
timeZone = 'Asia/Tokyo'
title = 'owasikohu.dev'
theme = 'owasikohu.dev'
disableKinds = ['rss', 'taxonomy', 'term']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
